FROM bash:latest

# hapi-server volume
VOLUME /hapi-server
ADD ./hapi-server /hapi-server

# hapi-server-initializer volume
VOLUME /hapi-server-initializer
ADD ./hapi-server-initializer /hapi-server-initializer

# Loop script to avoid termination of container.
ADD ./loop.sh /loop.sh

CMD [ "/loop.sh" ]
