version: '2.1'
services:
   medarbejder-bff:
     image: kvalitetsit/hjemmebehandling-medarbejder-bff:dev
     ports:
      - 8080:8080
      - 5005:5005
     environment:
      - cpr_url=http://person-service:1081/Patient/

      - allowed_origins=http://localhost:3000

      - user.context.handler=MOCK
      - user.mock.context.organization.id=123456
      #- user.mock.context.organization.id=453071000016001

      - usercontext_header_name=X-Test-Auth

      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation

      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole

      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

   hapi-server:
     image: hapiproject/hapi:latest
     environment:
       - hapi.fhir.allow_external_references=true
       - hapi.fhir.expunge_enabled=true
       - hapi.fhir.reuse_cached_search_results_millis=1000
       - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006
     ports:
       - 8082:8080
       - 5006:5006

   hapi-server-initializer:
     image: kvalitetsit/hjemmebehandling-data-initializer:latest
     depends_on:
       - hapi-server
     environment:
       - init_test_data=true

   person-service:
     image: mockserver/mockserver
     command: -logLevel DEBUG -serverPort 1081
     environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
     ports:
      - 1081:1081
     volumes:
      - ./person-service/initializerJson.json:/config/initializerJson.json
