version: '3.9'
services:
   medarbejder-bff:
     image: kvalitetsit/hjemmebehandling-medarbejder-bff:dev
     ports:
      - 8080:8080
      - 5005:5005
     environment:
      - cpr_url=http://person-service:1081/Patient/
      - allowed_origins=http://localhost:3000
      - user.context.handler=MOCK
      - user.mock.context.organization.id=123456
      - usercontext_header_name=X-Test-Auth
      - userattributes_role_key=UserRoles
      - userattributes_org_key=organisation
      - userrole_admin_values=adminrole
      - userrole_user_values=userrole1,userrole2
      - userrole_monitor_values=monitorrole
      - userrole_provisioner_values=provisionerrole
      - JVM_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

   hapi-server:
     image: kvalitetsit/hjemmebehandling-hapi-fhir-server:dev
     environment:
       - spring.datasource.url=jdbc:postgresql://postgres:5432/hapi
       - spring.datasource.username=hapi
       - spring.datasource.password=hapi
     ports:
       - 8082:8080
       - 8083:8081
     depends_on:
       - postgres
     healthcheck:
       test: [ "CMD", "curl", "-f", "http://localhost:8080/fhir/metadata" ]
       interval: 1m
       timeout: 10s
       retries: 3
       start_period: 40s

   hapi-server-initializer:
     image: kvalitetsit/hjemmebehandling-data-initializer:latest
     depends_on:
       hapi-server:
         condition: service_healthy
     environment:
       - init_test_data=true
       - init_questionnaire_and_plandefinition_infektionsmedicinsk=true
   person-service:
     image: mockserver/mockserver
     command: -logLevel DEBUG -serverPort 1081
     environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
     ports:
      - 1081:1081
     volumes:
      - ./person-service/initializerJson.json:/config/initializerJson.json
      
   custom-login-service:
     image: mockserver/mockserver
     command: -logLevel DEBUG -serverPort 1082
     environment:
      - MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
     ports:
      - 1082:1082
     volumes:
      - ./custom-login-service/initializerJson.json:/config/initializerJson.json


   postgres:
     image: postgres:16-alpine
     environment:
       - POSTGRES_USER=hapi
       - POSTGRES_PASSWORD=hapi
       - POSTGRES_ROOT_PASSWORD=hapi
       - POSTGRES_DATABASE=hapi
     ports:
       - 5432:5432